module.exports = {
  config: {
    updateChannel: 'stable',
    fontSize: 12,
    fontFamily:
      '"Fira Code", Hack, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
    cursorShape: 'BLOCK',
    cursorBlink: true,
    foregroundColor: '#fff',
    backgroundColor: '#000',
    css: ``,
    termCSS: ``,
    showHamburgerMenu: '',
    showWindowControls: '',
    padding: '10px 16px',
    shell: 'zsh',
    shellArgs: ['--login'],
    env: {},
    bell: false,
    copyOnSelect: false,
  },
  plugins: [
    'hypercwd',
    'hyper-always-on-top',
    'hyper-dracula',
    'hyper-hide-title',
    'hyper-font-ligatures',
  ],
  localPlugins: [],
  keymaps: {},
};
